FROM ubuntu:latest

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    apt update && \
    apt install -y wget gnupg && \
    wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add - && \
    echo "deb https://pkg.jenkins.io/debian-stable binary/" >> /etc/apt/sources.list && \
    apt update && \
    apt install -y jenkins openjdk-11-jre

EXPOSE 8080/TCP

ENTRYPOINT ["java"]
CMD ["-jar", "/usr/share/jenkins/jenkins.war"]
