FROM archlinux:latest

USER root

RUN patched_glibc=glibc-linux4-2.33-4-x86_64.pkg.tar.zst && \
curl -LO "https://repo.archlinuxcn.org/x86_64/$patched_glibc" && \
bsdtar -C / -xvf "$patched_glibc"

RUN pacman-db-upgrade
RUN pacman -Syu --noconfirm --needed ponysay

ENTRYPOINT ["/usr/bin/ponysay"]
CMD ["So you're a unicorn pony now?”]
