kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: log-watcher-bind
  namespace: default
subjects:
- kind: User
  name: system:serviceaccount:default:log-reader
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: log-watcher
  apiGroup: rbac.authorization.k8s.io
