apiVersion: v1
kind: Pod
metadata:
  name: shared-volumes-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: "/static"
      name: static
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: "/tmp/cache"
      name: static
  volumes:
  - name: static
    emptyDir: {}
